version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'actions/*'
        update-types:
          - version-update:semver-major
