name: Debug log
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      SECRETVALUE: SuperSecretValue
    steps:
      - run: echo "::debug::This is a debug log"
      - run: |
          set -x
          date
          hostname
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
          echo "::group::Show current directory"
          pwd
          echo "::endgroup::"
      - run: echo "::add-mask::${SECRETVALUE}"
      - run: echo "${SECRETVALUE}"
