name: Dump
on: push
defaults:
  run:
    shell: bash
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dump
        id: dump
        uses: ./.github/actions/dump/
        with:
          enable-context: 'true'
      - name: show date
        run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}
