name: Literals
run-name: Literals by @${{ github.actor }}
on: push
jobs:
  print:
    # if: ${{ github.actor == 'octocat' }}
    name: Print Literals And Functions
    runs-on: ubuntu-latest
    steps:
      - name: Print Literals
        run: printenv | grep 'LITERAL_'
        env:
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 1234 }}
          LITERAL_STRING: ${{ 'Hello' }}
          LITERAL_OMIT_STRING: World
      - name: Print Functions
        run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}
          FORMAT_FUNC: ${{ format('{0}, {1}!', 'Hello', 'World') }}
          JOIN_FUNC: ${{ join(github.event.commits.message, ', ') }}
          TO_JSON_FUNC: ${{ toJson(github.event) }}
          HASH_FILES_FUNC: ${{ hashFiles('.github/workflows/*.yml') }}
      - name: Print Hello
        run: echo "Hello"
        if: ${{contains(github.run_id, '1') }}
      # - run: exit 1
      - name: Print World if Failure
        run: echo "World"
        if: ${{ failure() }}
