name: Literals
on: push
jobs:
  print:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 1234 }}
          LITERAL_STRING: ${{ 'Hello' }}
          LITERAL_OMIT_STRING: World
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}
          FORMAT_FUNC: ${{ format('{0}, {1}!', 'Hello', 'World') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}
          TO_JSON_FUNC: ${{ toJson(github.event) }}
          HASH_FILES_FUNC: ${{ hashFiles('.github/workflows/*.yml') }}
      - run: echo "Hello"
        if: ${{contains(github.run_id, '1') }}
      - run: exit 1
      - run: echo "World"
        if: ${{ failure() }}
