name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: Hello
        required: true
        default: A cheerful word
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
