name: Parallel jobs
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        run: echo "result=Hello" >>"${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.generate.outputs.result }}
  second:
    runs-on: ubuntu-latest
    needs: [first]
    steps:
      - env:
          RESULT: ${{ needs.first.outputs.result }}
        run: echo "${RESULT}"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job"
  fourth:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [18, 20]
    runs-on: ${{ matrix.os }}
    needs: [second, third]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${RUNNER_OS}" && node --version
