name: Static analysis
on:
  pull_request:
    paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
defaults:
  run:
    shell: bash
jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
