name: Test
on:
  pull_request:
    paths: ['go/**/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4.2.1
        with:
          go-version-file: go.mod
      - run: go test go/excellent/*.go
